modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="minecoloniesxaero"
version="${file.jarVersion}"
displayName="MineColonies Xaero Claim"
authors="Kai"
description='''
Client-side diagnostic mod for detecting MineColonies claim data.
'''

displayTest="IGNORE_SERVER_VERSION"

[[dependencies.minecoloniesxaero]]
modId="neoforge"
type="required"
versionRange="[21.1.233,)"
ordering="NONE"
side="CLIENT"

[[dependencies.minecoloniesxaero]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"

[[dependencies.minecoloniesxaero]]
modId="minecolonies"
type="required"
versionRange="[1.1.1294,)"
ordering="NONE"
side="CLIENT"

[[dependencies.minecoloniesxaero]]
modId="xaeroworldmap"
type="optional"
versionRange="[1.44.2,)"
ordering="NONE"
side="CLIENT"